### ISSUE TITLE
known gene partners

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/fusions#13]
We should extend Figure B to also include known gene partners associated with a multi-partner categorical fusion. For example, the knowledge of multiple distinct partners associated with a multi-gene fusion.

```yaml
fusion:
  structural_components:
    - compatible_gene:
        known_compatible:
          - gene:
              symbol: TPM3
              id: hgnc:12012
          - gene:
              symbol: LMNA
              id: hgnc:6636
    - gene:
        symbol: NTRK1
        id: hgnc:427
```

**Comment by ahwagner** [comment]
This may be extensible to other attributes as well, for example if compatible partner genes are expected to share functional characteristics? For example, if TPM3 and LMNA and other putative partners are viable by virtue of DNA-binding properties.

```yaml
fusion:
  structural_components:
    - compatible_gene:
        known_compatible:
          - gene:
              symbol: TPM3
              id: hgnc:12012
          - gene:
              symbol: LMNA
              id: hgnc:6636
        functional_characteristics:
          - label: DNA Binding
            id: GO:0003677
    - gene:
        symbol: NTRK1
        id: hgnc:427
```

This example is contrived; to my knowledge there is no shared 5' partner functional characteristic for NTRK1 fusions and nor are TPM3 and LMNA proteins known for DNA-binding functionality. However, I am raising this question in case there are known examples to consider in this space.
